# crime_categories.py

crime_categories = {
    'Gewaltverbrechen': [
        'OTHER ASSAULT',
        'ARSON',
        'EXTORTION',
        'CRIMINAL HOMICIDE',
        'ROBBERY',
        'BATTERY - SIMPLE ASSAULT',
        'BRANDISH WEAPON',
        'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT',
        'THEFT, PERSON',
        'SPOUSAL(COHAB) ABUSE - SIMPLE ASSAULT',
        'THREATS, VERBAL/TERRORIST',
        'SHOTS FIRED AT INHABITED DWELLING',
        'THREATENING PHONE CALLS/LETTERS',
        'CRIMINAL THREATS - NO WEAPON DISPLAYED',
        'ATTEMPTED ROBBERY',
        'STALKING',
        'DISCHARGE FIREARMS/SHOTS FIRED',
        'THROWING OBJECT AT MOVING VEHICLE',
        'ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER',
        'SPOUSAL (COHAB) ABUSE - AGGRAVATED ASSAULT',
        'BATTERY POLICE',
        'BOMB SCARE',
        'BATTERY ON A FIREFIGHTER',
        'WEAPONS POSSESSION/BOMBING',
        'SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT',
        'SHOTS INHABITED DWELLING',
        'BATTERY FIREMAN',
        'HOMICIDE (NON-UCR)',
        'SHOTS FROM MOVING VEHICLE',
        'MANSLAUGHTER, NEGLIGENT',
        'BATTERY POLICE (SIMPLE)'
    ],
    'Eigentumsdelikte': [
        'LYNCHING - ATTEMPTED',
        'LYNCHING',
        'THEFT, COIN MACHINE - GRAND ($950.01 & OVER)',
        'THEFT FROM PERSON - ATTEMPT',
        'BURGLARY',
        'THEFT, COIN MACHINE - PETTY ($950 & UNDER)',
        'THEFT PLAIN - PETTY (UNDER $400)',
        'BUNCO, PETTY THEFT',
        'VEHICLE – STOLEN',
        'THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER)',
        'BURGLARY FROM VEHICLE',
        'THEFT PLAIN - PETTY ($950 & UNDER)',
        'THEFT FROM MOTOR VEHICLE - PETTY ($950.01 & OVER)',
        'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD',
        'BURGLARY FROM VEHICLE, ATTEMPTED',
        'BUNCO, GRAND THEFT',
        'BIKE – STOLEN',
        'EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)',
        'SHOPLIFTING - PETTY THEFT ($950 & UNDER)',
        'BURGLARY, ATTEMPTED',
        'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)',
        'DRIVING WITHOUT OWNER CONSENT (DWOC)',
        'THEFT PLAIN - ATTEMPT',
        'THEFT FROM MOTOR VEHICLE – ATTEMPT',
        'PURSE SNATCHING',
        'VEHICLE - ATTEMPT STOLEN',
        'FALSE IMPRISONMENT',
        'SHOPLIFTING - ATTEMPT',
        'PICKPOCKET',
        'EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)',
        'BOAT - STOLEN',
        'TILL TAP - PETTY ($950 & UNDER)',
        'BUNCO, ATTEMPT',
        'FALSE POLICE REPORT',
        'DISHONEST EMPLOYEE - GRAND THEFT',
        'PURSE SNATCHING – ATTEMPT',
        'DISHONEST EMPLOYEE - PETTY THEFT',
        'TELEPHONE PROPERTY - DAMAGE',
        'GRAND THEFT / AUTO REPAIR',
        'THEFT FROM MOTOR VEHICLE - PETTY (UNDER $400)',
        'SHOPLIFTING - PETTY THEFT',
        'THEFT-GRAND (OVER $400 OR $100 IF FOWL)',
        'EMBEZZLEMENT, PETTY',
        'EMBEZZLEMENT, GRAND',
        'SHOPLIFTING-GRAND THEFT (OVER $401)',
        'THEFT, COIN MACHINE - PETTY',
        'PROPERTY MISSING RVD VEH - PETTY',
        'PETTY THEFT - AUTO REPAIR',
        'PROPERTY MISSING RVD VEH - GRAND',
        'TILL TAP – PETTY',
        'BIKE - ATTEMPTED STOLEN',
        'PICKPOCKET, ATTEMPT',
        'THEFT, COIN MACHINE – GRAND',
        'PROPERTY MISSING RVD VEH - PETTY ($950 & UNDER)',
        'PROPERTY MISSING RVD VEH - GRAND THEFT ($950.01 & OVER)',
        'TILL TAP - GRAND THEFT ($950.01 & OVER)',
        'GRAND THEFT / INSURANCE FRAUD',
        'DISHONEST EMPLOYEE ATTEMPTED THEFT',
        'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)'
    ],
    'Betrugsdelikte': [
        'CREDIT CD > $200',
        'CREDIT DD < $200',
        'DOCUMENT FORGERY / STOLEN FELONY',
        'DEFRAUDING INNKEEPER/THEFT OF SERVICES, OVER $400',
        'THEFT OF IDENTITY',
        'CREDIT CARDS, FRAUD USE ($950.01 & OVER)',
        'DEFRAUDING INNKEEPER/THEFT OF SERVICES, $400 & UNDER',
        'COUNTERFEIT',
        'DOCUMENT WORTHLESS ($200 & UNDER)',
        'CREDIT CARDS, FRAUD USE ($950 & UNDER)',
        'DOCUMENT WORTHLESS ($200.01 & OVER)',
        'DOCUMENT WORTHLESS > $100'
    ],
    'Cyberkriminalität': [
        'UNAUTHORIZED COMPUTER ACCESS'
    ],
    'Umweltkriminalität': [
        'CRUELTY TO ANIMALS'
    ],
    'Verkehrsdelikte': [
        'TRAFFIC DR #',
        'RECKLESS DRIVING',
        'FAILURE TO YIELD',
        'DRUNK ROLL'
    ],
    'Sexualdelikte': [
        'PEEPING TOM',
        'SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH',
        'LEWD CONDUCT',
        'INDECENT EXPOSURE',
        'PANDERING',
        'LETTERS, LEWD',
        'RAPE, FORCIBLE',
        'RAPE, ATTEMPTED',
        'SEX, UNLAWFUL',
        'BATTERY WITH SEXUAL CONTACT',
        'ORAL COPULATION',
        'SEXUAL PENTRATION WITH A FOREIGN OBJECT',
        'PIMPING',
        'SEX OFFENDER REGISTRANT INCIDENT',
        'INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES)'
    ],
    'Ordnungswidrigkeiten': [
        'BLOCKING DOOR INDUCTION CENTER',
        'VANDALISM - FELONY',
        'VANDALISM - MISDEAMEANOR',
        'BIGAMY',
        'FAILURE TO DISPERSE',
        'VIOLATION OF RESTRAINING ORDER',
        'VANDALISM - MISDEAMEANOR ($399 OR UNDER)',
        'VIOLATION OF COURT ORDER',
        'VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)',
        'TRESPASSING',
        'VIOLATION OF TEMPORARY RESTRAINING ORDER',
        'RESISTING ARREST',
        'DISTURBING THE PEACE',
        'PROWLER',
        'ILLEGAL DUMPING',
        'CONTEMPT OF COURT',
        'ABORTION/ILLEGAL',
        'REPLICA FIREARMS(SALE,DISPLAY,MANUFACTURE OR DISTRIBUTE)',
        'INCITING A RIOT'
    ],
    'Jugendkriminalität': [
        'CONTRIBUTING'
    ],
    'Tierschutzverbrechen': [
        'CRUELTY TO ANIMALS',
        'BEASTIALITY, CRIME AGAINST NATURE SEXUAL ASLT WITH ANIM'
    ],
    'Kindesmisshandlung': [
        'CHILD ENDANGERMENT/NEG.',
        'CHILD STEALING',
        'KIDNAPPING',
        'CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT',
        'CHILD NEGLECT (SEE 300 W.I.C.)',
        'CHILD ANNOYING (17YRS & UNDER, DID NOT TOUCH VICTIM)',
        'CHILD, CRIME AGAINST',
        'KIDNAPPING - GRAND ATTEMPT',
        'CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT',
        'CHILD ABANDONMENT',
        'DRUGS, TO A MINOR',
        'CHILD ANNOYING (17YRS & UNDER)'
    ],
    'Sonstiges': [
        'OTHER MISCELLANEOUS CRIME',
        'CONSPIRACY'
    ]
}


# def categorize_crime(description):
#     for category, crimes in crime_categories.items():
#         if description in crimes:
#             return category
#     return 'Unbekannt'  # Für Verbrechen, die nicht im Dictionary vorhanden sind

# # Füge die "Crime Categorie"-Spalte hinzu
# data['Crime Categorie'] = data['CrmCd.Desc'].apply(categorize_crime)
